// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { crossSubdomainStorage } from './sessionStorageAdapter';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Cookie-backed and scoped to .optimustesting.com so one sign-in carries
    // across the app host and every company subdomain alias. See the adapter
    // for why localStorage isn't usable here.
    storage: crossSubdomainStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});