#!/usr/bin/env python3
"""Emit a migration that seeds outreach_drafts from the generated email drafts.

The drafts are authored in Python (templates + per-company hooks) but have to
live in the database for the admin panel to show, edit and send them. Rather
than duplicating the copy by hand into SQL, this renders the same drafts the
markdown file uses and writes them as INSERTs.

Contacts are matched by email against lead_contacts, and leads by company name,
both resolved in SQL at apply time rather than by hardcoded uuid -- the seed has
to work against whatever ids the target database already has.

Idempotent: ON CONFLICT on the unique contact index does nothing, so re-applying
never produces a second draft to the same person.

    python3 scripts/gen_draft_seed.py            # INSERTs, for a fresh database
    python3 scripts/gen_draft_seed.py --update   # UPDATEs, to re-sync already-seeded rows

The --update form exists because the copy is edited after it has been seeded.
It rewrites only rows still in DRAFT: a SENT row is the record of what actually
went out, and rewriting it would make the row disagree with the copy sitting in
the recipient's inbox.
"""

import sys
import pathlib

REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / 'scripts'))

from gen_send_queue import build_entries, clean  # noqa: E402
from gen_email_drafts import render_draft  # noqa: E402


def q(value):
    """SQL string literal, or NULL."""
    if value is None or value == '':
        return 'NULL'
    return "'" + str(value).replace("'", "''") + "'"


HEADER = """-- Seeds the phase-1 outreach drafts into outreach_drafts.
--
-- Generated by scripts/gen_draft_seed.py from the same templates and per-company
-- hooks that produce docs/sales/EMAIL_DRAFTS.md, so the copy cannot drift between
-- what is reviewed in the repo and what the panel sends.
--
-- Lead and contact are resolved by name and address at apply time rather than by
-- hardcoded uuid, because the ids differ per environment. A draft whose contact
-- cannot be resolved is skipped rather than inserted with a free-text address --
-- send_outreach_draft refuses to send without a linked contact, so a row like
-- that would be dead weight.
--
-- Idempotent: ON CONFLICT DO NOTHING against the unique contact index, so
-- re-applying cannot produce a second draft to the same person.
"""

UPDATE_STATEMENT = """
UPDATE public.outreach_drafts d
   SET subject = {subject}, body = {body}
  FROM public.lead_contacts c
 WHERE d.contact_id = c.id
   AND lower(c.email) = lower({email})
   AND d.status = 'DRAFT';
"""

UPDATE_HEADER = """-- Re-syncs the seeded outreach drafts with the current templates.
--
-- Generated by scripts/gen_draft_seed.py --update. Only DRAFT rows are touched:
-- a SENT row records what actually went out, and rewriting it would make the row
-- disagree with the copy in the recipient's inbox.
"""

STATEMENT = """
INSERT INTO public.outreach_drafts (lead_id, contact_id, to_email, to_name, subject, body)
SELECT l.id, c.id, {email}, {name}, {subject}, {body}
  FROM public.leads l
  JOIN public.lead_contacts c ON c.lead_id = l.id AND lower(c.email) = lower({email})
 WHERE l.company_name = {company}
ON CONFLICT (contact_id) WHERE contact_id IS NOT NULL DO NOTHING;
"""


def main():
    update_mode = '--update' in sys.argv
    entries, _ = build_entries()
    phase1 = [e for e in entries if e['tier'] in ('SMALL', 'MID')]

    out = [UPDATE_HEADER if update_mode else HEADER]
    for entry in phase1:
        subject, message = render_draft(entry)
        to = entry['to']
        if update_mode:
            out.append(UPDATE_STATEMENT.format(
                email=q(to['email']), subject=q(subject), body=q(message),
            ))
        else:
            out.append(STATEMENT.format(
                email=q(to['email']),
                name=q(clean(to.get('name')) or None),
                subject=q(subject),
                body=q(message),
                company=q(entry['company']),
            ))
    sys.stdout.write(''.join(out))


if __name__ == '__main__':
    main()
