#!/usr/bin/env python3
"""Generate the leads seed migration from the GTM target list.

One-shot generator: transcribes the master target table (deduped) into an
idempotent INSERT migration. Re-runnable; the migration guards on company_name.
"""
import sys

# (company_name, segment, region, size_signal, why_fit, buyer_title,
#  outreach_approach, priority, confidence, source_url, contact_name, contact_phone)
LEADS = [
    ("INEL Power Group", "Pure T&C contractor", "Chennai (branches: Bengaluru, Hyderabad)",
     "400+ engineers, 100+ support staff, ₹27 Cr turnover, licenses in TN/AP/MH/KA",
     "Since 1997; testing, commissioning, PM, O&M from 400V to 400kV across power, oil & gas, steel, cement; 100+ sites concurrent",
     "Head - Testing & Commissioning",
     "Direct LinkedIn + phone; reference from TANGEDCO/TSGENCO project connections",
     5, "High", "https://www.inelpse.com", None, None),
    ("GK Expertise / GK Power Expertise Pvt Ltd", "Pure T&C / relay & substation specialist", "Chennai (HQ), Oman branch",
     "50-200 engineers, multi-country; explicit relay testing, circuit breaker, transformer, SCADA commissioning",
     "Dedicated T&C company using OMICRON, Megger, Doble; programs all major relay makes; AIS & GIS; writes site test reports",
     "Technical Director / Head of T&C",
     "LinkedIn Sales Navigator; demonstrate auto-drafted commissioning report",
     5, "High", "https://www.gkexpertise.com", None, None),
    ("Chamunda Electrical Ltd", "Pure T&C contractor + O&M", "Palanpur, Gujarat",
     "501-1000 employees, ₹5-25 Cr turnover, recently went public (NSE Emerge, Feb 2025)",
     "Core business: T&C of substations up to 220kV + O&M up to 66kV; GETCO-approved; founder has 30 years ex-GEB experience",
     "MD / Operations Head",
     "Email + founder outreach via NSE disclosure contacts; pitch efficiency gain as they scale post-IPO",
     5, "High", "https://firstindia.co.in/news/press-releases/chamunda-electrical-limited-raises-rs-41100-lakhs-from-anchor-investors-ahead-of-its-ipo", None, None),
    ("Elite Powertech Pvt Ltd (EPPL)", "Pure T&C + EPC", "Pan-India (field teams)",
     "200-500 engineers; T&C up to 765kV; solar O&M, EPC substations",
     "Dedicated T&C team for EHV substations up to 765kV; protection, SCADA, PMC, O&M - runs many projects simultaneously",
     "Head of T&C / Projects Director",
     "LinkedIn; show how report templates cut site-to-handover cycle",
     5, "High", "https://elitepowertech.in", None, None),
    ("MST Electrical Services Pvt Ltd", "Pure T&C + condition monitoring", "Sahibabad, Ghaziabad (Pan-India)",
     "TrustSEAL 14 yrs; field teams across India",
     "Substation Installation, Testing & Commissioning, Condition Monitoring and Diagnostic Testing; VCB, SF6CB, CT, PT, Transformer testing; pan-India",
     "Technical Head / Operations Manager",
     "IndiaMART + direct call; NCR-based makes in-person demo easy",
     5, "High", "https://m.indiamart.com/mstelectricalservices", None, None),
    ("Reliserv Solution India", "T&C + substation automation", "Navi Mumbai (Delhi, Bengaluru branches)",
     "50-200 engineers; founded 2019; growing fast",
     "Protection T&C, relay programming, AIS/GIS erection testing, SCADA - all voltage levels LV to EHV; branches in Mumbai, Delhi, Bengaluru",
     "Founder / Technical Director",
     "Direct outreach; WhatsApp + LinkedIn; close to your Navi Mumbai base",
     5, "High", "https://reliservsolutions.com", None, None),
    ("Eternergy Engineering Pvt Ltd", "T&C specialist - HV/LV systems", "India (projects in India & Australia)",
     "Mid-size; multi-industry (utilities, renewables, rail, commercial)",
     "Explicit T&C specialisation for EHV/HV substations, transformer yards, RMUs, pad-mount switchgear; IS standards-aligned",
     "Technical Director / Head of Commissioning",
     "Website form + LinkedIn; international experience signals structured reporting pain",
     5, "High", "https://eternergy.com.in/testing-and-commissioning", None, None),
    ("Transerect Testing & Commissioning Engineers Pvt Ltd", "Pure T&C", "Malleswaram, Bengaluru",
     "14 years on IndiaMART; calibration for relays, CTs, transformers, GIS, switchgear",
     "Company built purely around T&C; generators, transformers, HV/LV motors, GIS breakers; test report generation is core deliverable",
     "Proprietor / Technical Head",
     "LinkedIn Sales Navigator Karnataka filter; in-person Bengaluru demo",
     5, "High", "https://m.indiamart.com/transerect-testing-commissioning-eng", None, None),
    ("Powertest Asia Pvt Ltd (PtA)", "TPIA / independent testing & inspection", "Hyderabad (pan-India)",
     "ISO 9001; since 1995; serves OEMs, utilities, service providers",
     "Independent T&C + TPQI; tan delta, SFRA, ELCID, PDA, OMICRON suites; not tied to any OEM = unbiased report quality",
     "Managing Director / Chief Inspector",
     "LinkedIn + direct call; pitch as the digital layer under their test-cert workflow",
     5, "High", "https://powertestasia.com", None, None),
    ("Sun and Jay Engineering Consultants Pvt Ltd", "T&C + SCADA", "Mogappair, Chennai",
     "14 yrs; 2005-founded; serves ABB, Siemens, GE, SEL, Alstom relay makes",
     "Pre-commissioning tests, switchyard T&C, SCADA, relay testing, protection - Tamil Nadu / South India; multi-make relay expertise",
     "Deputy MD / Commissioning Head",
     "Phone + email via IndiaMART; Chennai office visit",
     5, "High", "https://m.indiamart.com/sun-jay-engineering/profile.html", None, None),
    ("M. Electricals & Enterprises", "T&C contractor (regional)", "Nagpur, Maharashtra",
     "Founded 1998; MSETCL, MSEDCL, NTPC, PWD, Indian Railways approved contractor",
     "EHV/HT/LT T&C, OHL, AMC, switchyard testing, transformer testing; Central India; clients include Reliance Industries, ABB, Lloyds Steel",
     "Proprietor",
     "Direct call; reference MSETCL work to establish credibility",
     5, "High", "https://m.indiamart.com/melectricals", "Sanjay Ghude", None),
    ("Omnific Solutions", "T&C services + test-kit rental", "Navi Mumbai / Nashik, Maharashtra",
     "Proprietorship, 11-25 employees, ₹1.5-5 Cr; TrustSEAL",
     "Pan-India substation T&C; SFRA, tan delta, relay testing, OMICRON kit rentals; 10-engineer field teams; Nashik base",
     "Proprietor",
     "Direct WhatsApp (listed on IndiaMART); close proximity to Mumbai",
     5, "High", "https://m.indiamart.com/omnificsolutions", "Manoj Shinde", None),
    ("Power Process Engineering India Pvt Ltd", "T&C + maintenance", "Chennai",
     "14 yrs; AMC substations up to 400kV; transformer, relay, steel plant T&C",
     "Testing, commissioning up to 400kV; AMC for power plants, cement, steel, paper; multi-sector = multi-site deployments",
     "Operations Head",
     "IndiaMART + direct call; Chennai engineering hub",
     5, "High", "https://m.indiamart.com/powerprocessengineering", None, None),
    ("Akuntha Projects Pvt Ltd", "EPC + T&C + O&M substations", "Gujarat (Kutch + pan-Gujarat)",
     "50-200 staff; GETCO-registered contractor; manages several dozens of substations",
     "Substation erection, T&C, O&M, solar EPC; manages dozens of substations concurrently = high test-record volume pain",
     "Operations Director",
     "LinkedIn + website contact; Gujarat base aligns with GETCO expansion",
     5, "High", "https://akuntha.com", None, None),
    ("ARRAA Energy", "Relay testing specialist", "Chennai area",
     "Small specialist team; OMICRON, Megger, Doble",
     "All protection relay types; IEC/IEEE-compliant; explicit relay testing service with formal test reports; quick-win target",
     "Founder",
     "Direct call (+91 90433 23091) listed on website",
     5, "High", "https://www.arraaenergy.com/relay-testing.php", None, "+91 90433 23091"),
    ("Ohms Tech Engineers", "T&C - GIS / switchyard", "Villivakkam, Chennai",
     "Founded 2011; TradeIndia verified",
     "T&C of GIS substations, switchyards, power plants, commercial MV/LV panels; Substation and Relay Testing Services",
     "Proprietor / Technical Head",
     "TradeIndia + phone; Chennai cluster targeting",
     5, "High", "https://www.tradeindia.com/products/substation-and-relay-testing-services-2396803.html", None, None),
    ("Accenture Instrumentation and Automation", "T&C + SCADA commissioning", "Hyderabad",
     "4 yrs GST; small specialist firm (not affiliated with Accenture plc)",
     "Substation commissioning, measuring system installation/testing, SCADA, automation - Hyderabad Telangana hub",
     "Proprietor",
     "Direct IndiaMART / WhatsApp",
     5, "Medium", "https://m.indiamart.com/impcat/substation-commissioning.html", None, "8043863737"),
    ("Srinivasa Engineering Services", "T&C + AMC (regional)", "Secunderabad, Telangana",
     "Founded 2001; pan-Telangana",
     "Erection, AMC, testing, commissioning, circuit breaker servicing; AP/Telangana region",
     "Proprietor",
     "Direct IndiaMART call",
     5, "Medium", "https://www.indiamart.com/srinivasaengineering-services", None, None),
    ("Bhargavi Power Links", "T&C (regional)", "Visakhapatnam, AP",
     "GST 11 yrs; field services",
     "Substation commissioning services; AP coastal region; energization projects",
     "Owner",
     "IndiaMART / direct",
     5, "Medium", "https://m.indiamart.com/impcat/substation-commissioning.html", None, None),
    ("DCM Engineers", "T&C + compact substations", "Indore, MP",
     "4.3 rating on IndiaMART; MP/Gujarat/Maharashtra coverage",
     "Substation testing and commissioning; compact substation T&C; Central India",
     "Owner / Technical Lead",
     "Direct call; IndiaMART listing",
     5, "Medium", "https://m.indiamart.com/impcat/substation-testing-services.html", None, None),
    ("Rathasya Power Consultants", "Substation T&C + inspection", "Bengaluru",
     "12 yrs GST; Karnataka focus",
     "Field testing of transformers, erection supervision, commissioning services, substation O&M",
     "Proprietor",
     "IndiaMART + LinkedIn Karnataka search",
     5, "Medium", "https://m.indiamart.com/rathasya-power", None, None),
    ("E-Pillar Engineering Services", "T&C + relay testing", "India (IndiaMART listed)",
     "Small team",
     "High Qualified Engineers for T&C of substation, relay setting, AutoCAD drafting - multi-service T&C firm",
     "Technical Lead",
     "IndiaMART direct",
     5, "Medium", "https://m.indiamart.com/e-pillar-engineering-services", None, None),
    ("Pratiksha Enterprises", "Relay + HV testing services", "Kalyan, Maharashtra",
     "10+ yrs",
     "CT testing, relay testing, HT panel testing, insulation resistance testing - Maharashtra field teams",
     "Proprietor",
     "Direct call per website",
     5, "High", "https://www.pratikshaenterprises.co.in/testing-services.html", None, None),
    ("Invenia Systems", "Industrial T&C / commissioning", "Howrah, Kolkata",
     "8 yrs GST; EHV/LV rated; 4.0 rating",
     "Commissioning for industrial, power plant, oil & gas, cement, steel, data centres; HT, LT, EHV; Bengal hub",
     "Technical Head",
     "IndiaMART + LinkedIn East India filter",
     4, "Medium", "https://m.indiamart.com/impcat/electrical-commissioning-service.html", None, None),
    ("Hartek Power Pvt Ltd / Hartek Group", "T&D EPC - top 3 India", "Mohali, Punjab (pan-India)",
     "1,000+ employees; 400+ EHV/HV substation projects; 21 states",
     "India Top-3 substation EPC; 765kV, 400kV, solar + substation; multiple concurrent sites nationally",
     "Head of Commissioning / Project Director",
     "LinkedIn Sales Navigator; attend ELECRAMA / Hartek events; pilot at Punjab/Himachal project",
     4, "High", "https://hartek.com/business/power-system", None, None),
    ("Techno Electric & Engineering Co Ltd (TEECL)", "T&D EPC (large)", "Kolkata",
     "Listed; ~₹2,400 Cr revenue FY25; 17 active sites",
     "Substation EPC 765kV; 17 concurrent project sites; internal T&C teams; field engineers need digital test tracking",
     "Head of Commissioning / IT Head",
     "LinkedIn + annual report contacts; position as project tracking tool",
     4, "High", "https://www.techno.co.in", None, None),
    ("NCC Limited (Electrical T&D Division)", "T&D EPC", "Hyderabad",
     "Listed; large pan-India",
     "Expertise in EHV/HV substation ETC + transmission lines; RDSS/33-11kV substations in Maharashtra currently",
     "VP Electrical / Project Head T&D",
     "LinkedIn; cite Maharashtra RDSS substation recruitment",
     4, "High", "https://ncclimited.com/electrical.html", None, None),
    ("HEC Infra Projects Ltd", "EPC - substations + transmission", "Ahmedabad, Gujarat",
     "Listed (~₹135 Cr market cap); 300+ landmarks; GETCO + PowerGrid contractor",
     "SITC substations up to 220kV; GETCO license; PowerGrid contracts (400/220kV substation augmentation); field teams",
     "Director Operations / Project Manager",
     "LinkedIn; target Gujarat + Rajasthan field ops",
     4, "High", "https://tradebrains.in/hec-infra-projects-bags-11-89-cr-powergrid-order-for-substation-augmentation", None, None),
    ("Jyoti Structures Ltd", "T&D EPC (mid-large)", "Mumbai",
     "Listed; ₹165 Cr revenue FY25; 750+ employees",
     "Substation EPC 11kV-765kV; recently won ₹639 Cr order for 765kV/400kV TL; substation T&C embedded in EPC delivery",
     "Head - Substation Projects",
     "LinkedIn; target their commissioning/project management team",
     4, "High", "https://jyotistructures.in/sub-station", None, None),
    ("Powertech Consultants India Pvt Ltd", "Installation, T&C + SCADA", "Mumbai",
     "₹10-25 Cr turnover; 14 yrs",
     "Substation installation, testing, commissioning + SCADA automation; Mumbai base = Maharashtra projects",
     "Director / Technical Head",
     "IndiaMART + direct visit (Mumbai proximity)",
     4, "High", "https://www.indiamart.com/powertech-consultants-india-pvtltd", None, None),
    ("Srinivasa Engineering Projects Pvt Ltd", "Substation EPC + T&C", "Padi, Chennai",
     "11 yrs GST; partners with Ohms Tech for T&C",
     "HV substation installation; AIS/GIS up to 765kV (sub-contractor); T&C partnership with Ohms Tech",
     "Owner / Project Manager",
     "IndiaMART + direct call",
     4, "Medium", "https://m.indiamart.com/srinivasaconstruction/our-projects.html", None, None),
    ("Antique Power Pvt Ltd", "EHV substation EPC", "Morbi, Gujarat",
     "₹2-5 Cr turnover; GETCO-licensed",
     "Erection, commissioning, testing of EHV substations, EHV transmission lines, power plants; O&M; Gujarat-focused",
     "Proprietor / MD",
     "Direct call; Gujarat GETCO contractor network",
     4, "High", "https://www.indiamart.com/antique-power-private-limited", None, None),
    ("Voltage Infra Pvt Ltd", "Solar EPC + electrical contracting", "Pune, Maharashtra",
     "50-200 staff; fast-growing",
     "Solar EPC + conventional electrical contracting for government and private; substation O&M testing services",
     "Operations Head",
     "Website contact + LinkedIn Maharashtra",
     4, "High", "https://voltageinfra.com/service/om-and-testing-services-in-india", None, None),
    ("Power System & Controls", "T&C + installation", "Jalandhar, Punjab",
     "7 yrs GST; North India focus",
     "Substation commissioning, installation, construction; North India (Punjab, HP, J&K projects)",
     "Owner",
     "Direct call; IndiaMART listing",
     4, "Medium", "https://www.indianyellowpages.com/directory/substation-commissioning.htm", None, None),
    ("Gobind Electrical Corporation", "T&C (regional)", "Chandigarh",
     "15 yrs GST",
     "Substation testing and commissioning; North India / Chandigarh region",
     "Proprietor",
     "Direct call; IndiaMART",
     4, "Medium", "https://m.indiamart.com/impcat/substation-commissioning.html", None, None),
    ("Vedant Electricals & Filter Service", "Substation testing", "Thergaon, Pune",
     "4.6 rating, 12 yrs, TrustSEAL",
     "All substation equipment testing VCB, SF6CB, CT, PT, transformers, HT panels, HT cables; Pune base",
     "Proprietor",
     "IndiaMART + in-person Pune demo",
     4, "Medium", "https://m.indiamart.com/impcat/substation-testing-services.html", None, None),
    ("Aadhar Project and Electrical Services", "Substation installation + T&C", "Bhopal, MP",
     "8 yrs GST",
     "33kV substation installation, testing, commissioning pan-India; Madhya Pradesh base",
     "Owner",
     "Direct call",
     4, "Medium", "https://m.indiamart.com/impcat/substation-commissioning.html", None, None),
    ("Nu-tek Power Controls and Automation", "Substation commissioning", "Electronic City, Bengaluru",
     "Multi-year listing",
     "Substation commissioning; solar panel; electrical contractors; Bengaluru tech-adjacent hub",
     "Owner",
     "IndiaMART + LinkedIn Karnataka",
     4, "Medium", "https://www.indianyellowpages.com/directory/substation-commissioning.htm", None, None),
    ("Shivam Electrical Engineering", "Substation contractor", "Navi Mumbai / Thane",
     "3.4 rating IndiaMART",
     "Indoor/outdoor substation installation and testing; Mumbai metro region",
     "Owner",
     "Direct IndiaMART",
     4, "Medium", "https://m.indiamart.com/impcat/substation-electrical-contractor.html", None, None),
    ("Inel Power System Engineers Pvt Ltd", "T&C + relay testing instruments", "Jafferkhanpet, Chennai",
     "12 yrs GST; part of INEL Power Group cluster",
     "Testing & commissioning + relay test kit services, preventive maintenance; INEL subsidiary",
     "Technical Head",
     "Direct call or through INEL parent",
     4, "High", "https://m.indiamart.com/inel-power-system-engineers-p-ltd", None, None),
    ("Capex Electrical and Electronics Pvt Ltd", "Substation commissioning", "Warje, Pune",
     "IndiaMART listed",
     "Substation commissioning, APFC panel, HT busbar; Pune manufacturing belt",
     "Owner",
     "IndiaMART",
     4, "Medium", "https://www.indianyellowpages.com/directory/substation-commissioning.htm", None, None),
    ("JBS Enterprises Pvt Ltd", "Substation commissioning", "Thane, Maharashtra",
     "IndiaMART listed",
     "Substation commissioning + energy generation services; Mumbai-Thane cluster",
     "Director",
     "Direct approach",
     4, "Medium", "https://www.indianyellowpages.com/directory/substation-commissioning.htm", None, None),
    ("Transgear Power Systems Pvt Ltd", "Substation EPC / T&C", "Bengaluru",
     "10 yrs, TrustSEAL, 100% response rate",
     "11kV-33kV package substations supply, installation, testing, commissioning; Karnataka utility projects",
     "Owner",
     "IndiaMART",
     4, "Medium", "https://m.indiamart.com/impcat/electrical-substation-installation-services.html", None, None),
    ("Brooklyn Transformers & Electricals", "Substation installation + T&C", "Ahmedabad",
     "4.6 rating IndiaMART, 11 yrs",
     "Substation installation services Ahmedabad; Gujarat utility corridor",
     "Owner",
     "IndiaMART",
     4, "Medium", "https://m.indiamart.com/impcat/electrical-substation-installation-services.html", None, None),
    ("Prayas Electro Systems Thane Pvt Ltd", "Transformer testing + T&C", "Airoli, Navi Mumbai",
     "13 yrs GST",
     "Transformer tan delta, SFRA, protection relay healthiness; oil leak solutions; Mumbai T&C cluster",
     "Director",
     "IndiaMART",
     4, "Medium", "https://m.indiamart.com/proddetail/transformers-testing-10594319191.html", None, None),
    ("N. S. Thermal Energy Pvt Ltd", "Substation commissioning", "Ghaziabad, UP",
     "IndiaMART listed",
     "Electrical substation commissioning pan-India; UP/Delhi NCR operations",
     "Owner",
     "Direct call; IndiaMART",
     3, "Medium", "https://www.indianyellowpages.com/directory/substation-commissioning.htm", None, None),
    ("Manipal Energy & Infratech Ltd", "EPC (civil + electrical)", "Udupi, Karnataka",
     "Small-mid; GST listed",
     "EPC civil + mechanical + electrical, substations; Karnataka coast projects",
     "MD / Operations",
     "IndiaMART",
     3, "Medium", "https://m.indiamart.com/manipalenergy-infratech", None, None),
    ("SR Industry", "Substation contractor", "Kanpur, UP",
     "4.3 rating, 6 yrs",
     "Turnkey substations up to 400kV; UP industrial belt",
     "Owner",
     "IndiaMART",
     3, "Medium", "https://m.indiamart.com/impcat/substation-electrical-contractor.html", None, None),
    ("Subuna Power Controls", "Panel mfr + commissioning", "Balanagar, Hyderabad",
     "20 yrs; Telangana",
     "Substation erection, commissioning + panel manufacturing; 33kV; Hyderabad industrial cluster",
     "Owner",
     "Direct / IndiaMART",
     3, "Medium", "https://www.subunapower.com", None, None),
    ("Gayatri Energy Corporation", "Substation contractor", "Karjan, Vadodara",
     "Verified Exporter, 4 yrs",
     "11kV-400kV substation supply + installation; Gujarat corridor",
     "Owner",
     "IndiaMART",
     3, "Medium", "https://m.indiamart.com/impcat/substation-electrical-contractor.html", None, None),
    ("AD Worldwidetech Co.", "Substation installation", "Greater Noida, UP",
     "4.1 rating, TrustSEAL, 12 yrs",
     "Electrical substation installation pan-India, 11kV; NCR",
     "Director",
     "IndiaMART",
     3, "Medium", "https://m.indiamart.com/impcat/electrical-substation-installation-services.html", None, None),
    ("Sachin Electricals Pvt Ltd", "Electrical contractor + T&C", "Pan-India",
     "10+ yrs",
     "Substation installation up to 66kV + testing; HT/LT; cable laying; turnkey",
     "MD",
     "IndiaMART",
     3, "Medium", "https://www.indiamart.com/sachinelectricals", None, None),
    ("Sunpower India Ventures Pvt Ltd", "Electrical EPC + T&C", "Pan-India (LinkedIn listed)",
     "LinkedIn company page",
     "Electrical EPC; power evacuation; substation + transmission line; O&M",
     "Director Operations",
     "LinkedIn",
     3, "Medium", "https://in.linkedin.com/company/sunpower-india-ventures-pvt-ltd", None, None),
    ("R V Solar Power System", "Solar + substation commissioning", "Bengaluru",
     "TrustSEAL 8 yrs, 5.0 rating",
     "Substation electrical panel commissioning pan-India; solar + conventional",
     "Owner",
     "IndiaMART",
     3, "Medium", "https://m.indiamart.com/impcat/electrical-commissioning-service.html", None, None),
    ("Voltech Transformer Services OPC Pvt Ltd", "Transformer testing", "Baheri, UP",
     "2 yrs GST",
     "NABL-lab transformer oil testing, cable testing; UP operations",
     "Owner",
     "IndiaMART",
     3, "Medium", "https://m.indiamart.com/voltechtransformerservices", None, None),
    ("Waaree Energies Ltd", "Solar EPC + O&M", "Mumbai",
     "Listed; 15 GW module capacity; large EPC arm",
     "India's largest solar module maker; EPC + O&M arm energizes substations for every project; internal T&C teams",
     "VP O&M / Head of Projects",
     "LinkedIn Sales Navigator; Waaree EPC procurement team; ELECRAMA/REI events",
     3, "High", "https://waareeenergies.com", None, None),
    ("Vikram Solar Ltd", "Solar EPC + O&M", "Kolkata",
     "Listed Aug 2025; 9.5 GW capacity",
     "Solar EPC + O&M; energises project substations; T&C teams at every project site",
     "Head - O&M / Project Commissioning",
     "LinkedIn; attend Solar India conference",
     3, "High", "https://vikramsolar.com", None, None),
    ("Premier Energies Ltd", "Solar EPC", "Hyderabad",
     "Listed; growing EPC arm",
     "Solar cell + module manufacturer + EPC; T&C embedded in project delivery",
     "Head of EPC Projects",
     "LinkedIn",
     3, "High", "https://premierenergies.com", None, None),
    ("SPML Infra Ltd", "Infrastructure EPC (incl. power)", "New Delhi",
     "Listed; ₹13 Cr market cap",
     "BESS + power EPC; substation integration; DISCOM projects",
     "VP Projects",
     "LinkedIn",
     3, "High", "https://www.spml.co.in", None, None),
    ("G R Infraprojects Ltd (Power Division)", "T&D EPC", "Udaipur / New Delhi",
     "Listed; power T&D growing division",
     "Substation EPC + T&L; 400/220kV AIS; Rajgarh project commissioned 2024",
     "Business Unit Head - Power Transmission",
     "LinkedIn; target BU head directly",
     3, "High", "https://www.grinfra.com/power", None, None),
    ("HCK Solar", "Solar EPC", "Kolkata",
     "8 MW first year; growing",
     "New entrant; solar EPC; substation commissioning involved",
     "Founder / MD",
     "LinkedIn",
     3, "Medium", "https://in.linkedin.com/in/chandan-singh-8ba546a", None, None),
    ("Bharat Test House Pvt Ltd (BTHPL)", "NABL testing lab (electrical + solar)", "Delhi NCR",
     "Large multi-lab; NABL accredited",
     "Multi-disciplinary testing including electrical; solar PV; BIS/NABL approved; some substation equipment testing",
     "Lab Head / Technical Director",
     "Email + lab directory",
     3, "High", "https://www.bharattesthouse.com", None, None),
    ("Ghaziabad Testing Laboratories Pvt Ltd", "NABL testing lab", "Ghaziabad, UP",
     "NABL TC:11707; ISO-certified; top-3 electrical testing lab India",
     "HV/MV testing (MV circuit disconnectors, earthing switches, contactors); independent NABL lab",
     "Lab Manager / Technical Head",
     "Direct via website + NABL directory",
     3, "High", "https://gtllab.org/electrical-testing-lab-in-delhi-india", None, None),
    ("Global EPC India Pvt Ltd (Vijayawada)", "Electro-technical testing", "Vijayawada, AP",
     "NABL accredited CC-3022",
     "NABL Electro-Technical scope; AP operations; substation equipment testing adjacent",
     "Lab Head",
     "NABL directory + direct",
     3, "High", "https://nabl-india.org", None, None),
    ("PSTCL (Punjab State Transmission Corp)", "State Transco", "Patiala, Punjab",
     "State utility; large fleet of substations",
     "Large testing & commissioning spend; Hartek has delivered 400kV reactor for them; mandates tools on contractors",
     "Head of T&C / GM Projects",
     "Govt procurement portal + PSTCL vendor registration",
     3, "High", "https://pstcl.org", None, None),
    ("APTRANSCO (AP Transco)", "State Transco", "Vijayawada, AP",
     "State utility; AP transmission expansion",
     "Large substation commissioning programme; AP power sector growth",
     "GM (T&C) / Chief Engineer",
     "AP Transco vendor portal",
     3, "High", "https://aptransco.gov.in", None, None),
    ("TSTRANSCO (Telangana Transco)", "State Transco", "Hyderabad",
     "State utility",
     "Telangana grid expansion; vendor base in Hyderabad cluster",
     "GM (Projects)",
     "TSTRANSCO vendor empanelment",
     3, "High", "https://www.tstransco.in", None, None),
    ("CSPTCL (Chhattisgarh State Power Transmission)", "State Transco", "Raipur, CG",
     "State utility",
     "Central India expansion; overlaps with M. Electricals & Enterprises client base",
     "Chief Engineer (T&C)",
     "State utility vendor portal",
     3, "High", "https://csptcl.co.in", None, None),
    ("UPPCL (Uttar Pradesh Power Corp Ltd)", "State DISCOM/Transco", "Lucknow, UP",
     "Largest state utility; 200M+ consumers",
     "Large substation commissioning wave under RDSS; NCR T&C contractor clusters",
     "GM Projects",
     "UPPCL empanelment portal",
     3, "High", "https://www.uppcl.org", None, None),
    ("MSEDCL (Maharashtra State Electricity Distribution Co.)", "State DISCOM", "Pune",
     "State utility; listed via MSEB",
     "MSEDCL-approved contractors do testing on MSEDCL's behalf; upstream influence",
     "Chief Engineer (T&C)",
     "MSEDCL GeM / vendor portal",
     3, "High", "https://www.mahadiscom.in", None, None),
    ("InGrid (IndiGrid Investment Managers)", "Private transmission infra", "Mumbai",
     "SEBI-listed InvIT; AUM ₹324B",
     "16 substations, 25,050 MVA transformation; TEECL executes projects; T&C embedded",
     "Asset Manager / Operations Head",
     "LinkedIn; TEECL connection",
     3, "High", "https://www.indigrid.co.in", None, None),
    ("Adani Energy Solutions (Adani Transmission)", "Private Transco + DISCOM", "Ahmedabad",
     "Large listed; large T&C programme",
     "Mumbai and western grid transmission; multiple substations; internal T&C teams + contractors",
     "Head of Commissioning",
     "LinkedIn; Adani procurement portal",
     3, "High", "https://www.adanienergysolutions.com", None, None),
    ("Power Mech Projects Ltd", "EPC + O&M (power)", "Secunderabad",
     "Listed; ₹5,000+ Cr revenue",
     "BOP, electrical works, substations; T&C embedded in project delivery",
     "Head - Electrical Projects",
     "LinkedIn",
     3, "High", "https://powermechprojects.com", None, None),
    ("MEIL (Megha Engineering & Infrastructure Ltd)", "Mega EPC", "Hyderabad",
     "Large private; power + infrastructure",
     "Power plants, substations, T&C; South + Central India; large field workforce",
     "VP - Electrical Projects",
     "LinkedIn",
     3, "High", "https://meghaengineering.com", None, None),
    ("Navayuga Engineering Co Ltd", "EPC", "Hyderabad",
     "Large private",
     "Power sector EPC; hydro + thermal + T&D",
     "Head of T&C",
     "LinkedIn + industry events",
     3, "Medium", "https://navayuga.com", None, None),
    ("SEPC Power / Sun Edison Power Construction", "Solar + industrial EPC", "Chennai",
     "Growing solar EPC; 650 Cr Maharashtra contract",
     "133 MW solar across 26 sites in Maharashtra (PM-KUSUM); each site energises a substation",
     "Project Head",
     "LinkedIn",
     3, "Medium", "https://www.sepc.in", None, None),
    ("Tata Power (T&C / O&M arm)", "Integrated power utility", "Mumbai",
     "Listed; large",
     "Tata Power Renewable Energy Ltd's EPC arm; solar + wind substations; DISCOM O&M in Delhi/Mumbai",
     "Head Commissioning RE",
     "LinkedIn; corporate procurement",
     3, "High", "https://www.tatapower.com", None, None),
    ("JSW Energy Ltd", "Private genco + solar IPP", "Mumbai",
     "Listed; 7+ GW capacity",
     "Solar + thermal plants; substations commissioned internally; T&C teams",
     "VP Projects",
     "LinkedIn; JSW energy procurement",
     3, "High", "https://www.jsw.in/energy", None, None),
    ("Torrent Power Ltd", "Integrated utility", "Ahmedabad",
     "Listed; Gujarat DISCOM + generation",
     "Large substation programme; commissioning of industrial + distribution substations",
     "AGM Projects",
     "LinkedIn",
     3, "High", "https://www.torrentpower.com", None, None),
    ("Tata Projects Ltd", "T&D EPC", "Hyderabad",
     "Large; Tata Group",
     "EPC including substations; T&C teams",
     "VP Projects (T&D)",
     "LinkedIn; Tata Projects procurement",
     2, "High", "https://tataprojects.com", None, None),
    ("KEC International Ltd", "T&D EPC", "Mumbai",
     "Listed; global",
     "Transmission lines + substations; T&C embedded",
     "Head of Commissioning",
     "LinkedIn; KEC annual conference",
     2, "High", "https://kecrpg.com", None, None),
    ("Kalpataru Projects International Ltd", "T&D EPC", "Mumbai",
     "Listed; large",
     "Substations + TL globally; in-house T&C",
     "VP Commissioning",
     "LinkedIn",
     2, "High", "https://www.kalpatarulimited.com", None, None),
    ("Sterling & Wilson (Pvt) Ltd", "Solar EPC + services", "Mumbai",
     "Listed; large",
     "Solar project EPC + O&M; commissioning substations",
     "Head EPC Projects",
     "LinkedIn",
     2, "High", "https://sterlingandwilson.com", None, None),
    ("L&T Power Transmission & Distribution", "T&D EPC", "Mumbai",
     "Very large",
     "Substation EPC 765kV; in-house T&C",
     "VP Commissioning",
     "LinkedIn + L&T procurement",
     2, "High", "https://www.larsentoubro.com", None, None),
    ("EMCO Ltd", "Transformer OEM + T&C services", "Mumbai",
     "Mid-large; listed",
     "Transformer testing at factory + on-site; could be integration partner",
     "Head of Service",
     "Direct / conference",
     2, "High", "https://www.emcotransformer.com", None, None),
    ("Doble Engineering (India)", "Test instrument OEM", "Bengaluru",
     "Mid-size India ops",
     "Doble test equipment used by all major T&C firms; integration/partner play",
     "Country Manager",
     "Direct business development",
     1, "High", "https://www.doble.com", None, None),
    ("OMICRON Electronics India", "Test instrument OEM", "India",
     "Small India team",
     "OMICRON test kits standard for relay testing; partner channel",
     "India Head",
     "Direct OEM partnership",
     1, "High", "https://www.omicronenergy.com", None, None),
    ("Megger India", "Test instrument OEM", "India",
     "Mid-size India ops",
     "Megger insulation testers used universally; partner/bundled play",
     "Country Sales Manager",
     "Partnership conversation",
     1, "High", "https://in.megger.com", None, None),
]


def q(val):
    if val is None:
        return "NULL"
    return "'" + str(val).replace("'", "''") + "'"


def main():
    # Guard against accidental dupes in source data.
    names = [r[0] for r in LEADS]
    dupes = {n for n in names if names.count(n) > 1}
    if dupes:
        sys.stderr.write(f"Duplicate company_name in source data: {dupes}\n")
        sys.exit(1)

    out = []
    out.append("-- Seed leads from the TestFlow GTM target list (deduped).")
    out.append("-- Generated by scripts/gen_leads_seed.py. Idempotent: skips rows whose")
    out.append("-- company_name already exists, so re-running is safe.")
    out.append("")
    out.append("INSERT INTO public.leads")
    out.append("  (company_name, segment, region, size_signal, why_fit, buyer_title,")
    out.append("   contact_name, contact_phone, outreach_approach, priority, confidence, source_url)")
    out.append("SELECT * FROM (VALUES")
    rows = []
    for (name, segment, region, size_signal, why_fit, buyer_title,
         outreach, priority, confidence, url, cname, cphone) in LEADS:
        rows.append(
            "  (" + ", ".join([
                q(name), q(segment), q(region), q(size_signal), q(why_fit),
                q(buyer_title), q(cname), q(cphone), q(outreach),
                str(priority), q(confidence), q(url),
            ]) + ")"
        )
    out.append(",\n".join(rows))
    out.append(") AS v(company_name, segment, region, size_signal, why_fit, buyer_title,")
    out.append("       contact_name, contact_phone, outreach_approach, priority, confidence, source_url)")
    out.append("WHERE NOT EXISTS (")
    out.append("  SELECT 1 FROM public.leads l WHERE l.company_name = v.company_name")
    out.append(");")
    out.append("")
    print("\n".join(out))
    sys.stderr.write(f"Generated {len(LEADS)} lead rows.\n")


if __name__ == "__main__":
    main()
