-- Re-syncs the seeded outreach drafts with the current templates.
--
-- Generated by scripts/gen_draft_seed.py --update. Only DRAFT rows are touched:
-- a SENT row records what actually went out, and rewriting it would make the row
-- disagree with the copy in the recipient's inbox.

UPDATE public.outreach_drafts d
   SET subject = 'Commissioning test records at Akuntha — from IIT Bombay', body = 'Mr Kamdar,

I''m Parakh Sharma, at IIT Bombay. I''ve built TestFlow — commissioning software
for substation testing teams. I got your address from akuntha.com.

What it does: your engineers record test results on site, offline if there''s no
signal. Supervisors approve from anywhere. The handover report — PDF and Excel —
generates itself when the project closes, instead of being assembled by hand
weeks later from whatever is on which laptop.

You''re running erection, T&C and O&M across Gujarat with a lot of substations live at once. That concurrency is exactly where test records stop being findable.

It''s live at https://optimustesting.com — worth a two-minute look before you
decide whether to reply.

I''d like to run one of your projects on it end to end, free. If it doesn''t save
your team time at handover, you''ve lost nothing but the call.

15 minutes this week?

Parakh Sharma
Optimus Testing
+91 94135 52887'
  FROM public.lead_contacts c
 WHERE d.contact_id = c.id
   AND lower(c.email) = lower('ravi@akuntha.com')
   AND d.status = 'DRAFT';

UPDATE public.outreach_drafts d
   SET subject = 'Commissioning test records at Transerect — from IIT Bombay', body = 'Mr Mahendra,

I''m Parakh Sharma, at IIT Bombay. I''ve built TestFlow — commissioning software
for substation testing teams. I got your address from transerect.com.

What it does: your engineers record test results on site, offline if there''s no
signal. Supervisors approve from anywhere. The handover report — PDF and Excel —
generates itself when the project closes, instead of being assembled by hand
weeks later from whatever is on which laptop.

Transerect is built purely around T&C, so the site test report isn''t a by-product for you — it is the deliverable. That''s the part this makes automatic.

It''s live at https://optimustesting.com — worth a two-minute look before you
decide whether to reply.

I''d like to run one of your projects on it end to end, free. If it doesn''t save
your team time at handover, you''ve lost nothing but the call.

15 minutes this week?

Parakh Sharma
Optimus Testing
+91 94135 52887'
  FROM public.lead_contacts c
 WHERE d.contact_id = c.id
   AND lower(c.email) = lower('mahendra@transerect.com')
   AND d.status = 'DRAFT';

UPDATE public.outreach_drafts d
   SET subject = 'For your T&C head — commissioning software from IIT Bombay', body = 'Hello,

I''m Parakh Sharma, at IIT Bombay. I''ve built commissioning software for
substation testing teams, and I got this address from your website. **If this
isn''t your area, please forward it to whoever runs testing & commissioning.**

What it does: engineers record test results on site, offline if there''s no
signal. Supervisors approve from anywhere. The handover report — PDF and Excel —
generates itself when the project closes, instead of being assembled by hand
weeks later.

You test every protection relay type on OMICRON, Megger and Doble, and hand over formal IEC/IEEE test reports at the end. Those kits each produce their own output; the report is still assembled afterwards. That assembly is what this removes.

It''s live at https://optimustesting.com — worth a two-minute look before you
decide whether to reply.

I''d like to run one of your projects on it end to end, free. If it doesn''t save
your team time at handover, you''ve lost nothing but the call.

15 minutes this week?

Parakh Sharma
Optimus Testing
+91 94135 52887'
  FROM public.lead_contacts c
 WHERE d.contact_id = c.id
   AND lower(c.email) = lower('enquiry@arraaenergy.com')
   AND d.status = 'DRAFT';

UPDATE public.outreach_drafts d
   SET subject = 'For your T&C head — commissioning software from IIT Bombay', body = 'Hello,

I''m Parakh Sharma, at IIT Bombay. I''ve built commissioning software for
substation testing teams, and I got this address from your website. **If this
isn''t your area, please forward it to whoever runs testing & commissioning.**

What it does: engineers record test results on site, offline if there''s no
signal. Supervisors approve from anywhere. The handover report — PDF and Excel —
generates itself when the project closes, instead of being assembled by hand
weeks later.

You''re running OMICRON, Megger and Doble across every major relay make, AIS and GIS, and writing site test reports off the back of all of it. The reports are the part I''m trying to make automatic.

It''s live at https://optimustesting.com — worth a two-minute look before you
decide whether to reply.

I''d like to run one of your projects on it end to end, free. If it doesn''t save
your team time at handover, you''ve lost nothing but the call.

15 minutes this week?

Parakh Sharma
Optimus Testing
+91 94135 52887'
  FROM public.lead_contacts c
 WHERE d.contact_id = c.id
   AND lower(c.email) = lower('enquiry@gkexpertise.com')
   AND d.status = 'DRAFT';

UPDATE public.outreach_drafts d
   SET subject = 'For your T&C head — commissioning software from IIT Bombay', body = 'Hello,

I''m Parakh Sharma, at IIT Bombay. I''ve built commissioning software for
substation testing teams, and I got this address from your website. **If this
isn''t your area, please forward it to whoever runs testing & commissioning.**

What it does: engineers record test results on site, offline if there''s no
signal. Supervisors approve from anywhere. The handover report — PDF and Excel —
generates itself when the project closes, instead of being assembled by hand
weeks later.

As an independent TPIA your report is the product — clients pay for its credibility precisely because you''re not tied to an OEM. Thirty years of that reputation is a lot to leave sitting in files on individual laptops.

It''s live at https://optimustesting.com — worth a two-minute look before you
decide whether to reply.

I''d like to run one of your projects on it end to end, free. If it doesn''t save
your team time at handover, you''ve lost nothing but the call.

15 minutes this week?

Parakh Sharma
Optimus Testing
+91 94135 52887'
  FROM public.lead_contacts c
 WHERE d.contact_id = c.id
   AND lower(c.email) = lower('info@powertestasia.com')
   AND d.status = 'DRAFT';

UPDATE public.outreach_drafts d
   SET subject = 'For your T&C head — commissioning software from IIT Bombay', body = 'Hello,

I''m Parakh Sharma, at IIT Bombay. I''ve built commissioning software for
substation testing teams, and I got this address from your website. **If this
isn''t your area, please forward it to whoever runs testing & commissioning.**

What it does: engineers record test results on site, offline if there''s no
signal. Supervisors approve from anywhere. The handover report — PDF and Excel —
generates itself when the project closes, instead of being assembled by hand
weeks later.

You cover ABB, Siemens, GE, SEL and Alstom relays across Tamil Nadu — every make with its own output format, and one coherent handover pack expected at the end of the job.

It''s live at https://optimustesting.com — worth a two-minute look before you
decide whether to reply.

I''d like to run one of your projects on it end to end, free. If it doesn''t save
your team time at handover, you''ve lost nothing but the call.

15 minutes this week?

Parakh Sharma
Optimus Testing
+91 94135 52887'
  FROM public.lead_contacts c
 WHERE d.contact_id = c.id
   AND lower(c.email) = lower('cv@sunjay.in')
   AND d.status = 'DRAFT';

UPDATE public.outreach_drafts d
   SET subject = 'For your T&C head — commissioning software from IIT Bombay', body = 'Hello,

I''m Parakh Sharma, at IIT Bombay. I''ve built commissioning software for
substation testing teams, and I got this address from your website. **If this
isn''t your area, please forward it to whoever runs testing & commissioning.**

What it does: engineers record test results on site, offline if there''s no
signal. Supervisors approve from anywhere. The handover report — PDF and Excel —
generates itself when the project closes, instead of being assembled by hand
weeks later.

You''re growing fast across solar EPC and substation O&M in Maharashtra. Growth is exactly when test records stop fitting in whatever worked at ten projects.

It''s live at https://optimustesting.com — worth a two-minute look before you
decide whether to reply.

I''d like to run one of your projects on it end to end, free. If it doesn''t save
your team time at handover, you''ve lost nothing but the call.

15 minutes this week?

Parakh Sharma
Optimus Testing
+91 94135 52887'
  FROM public.lead_contacts c
 WHERE d.contact_id = c.id
   AND lower(c.email) = lower('marketing@volt-age.in')
   AND d.status = 'DRAFT';

UPDATE public.outreach_drafts d
   SET subject = 'For your T&C head — commissioning software from IIT Bombay', body = 'Hello,

I''m Parakh Sharma, at IIT Bombay. I''ve built commissioning software for
substation testing teams, and I got this address from your website. **If this
isn''t your area, please forward it to whoever runs testing & commissioning.**

What it does: engineers record test results on site, offline if there''s no
signal. Supervisors approve from anywhere. The handover report — PDF and Excel —
generates itself when the project closes, instead of being assembled by hand
weeks later.

NABL accreditation means every result has to be traceable to who recorded it and when. That trail is kept automatically here rather than reconstructed when someone asks for it.

It''s live at https://optimustesting.com — worth a two-minute look before you
decide whether to reply.

I''d like to run one of your projects on it end to end, free. If it doesn''t save
your team time at handover, you''ve lost nothing but the call.

15 minutes this week?

Parakh Sharma
Optimus Testing
+91 94135 52887'
  FROM public.lead_contacts c
 WHERE d.contact_id = c.id
   AND lower(c.email) = lower('info@gtllab.org')
   AND d.status = 'DRAFT';

UPDATE public.outreach_drafts d
   SET subject = 'For your T&C head — commissioning software from IIT Bombay', body = 'Hello,

I''m Parakh Sharma, at IIT Bombay. I''ve built commissioning software for
substation testing teams, and I got this address from your website. **If this
isn''t your area, please forward it to whoever runs testing & commissioning.**

What it does: engineers record test results on site, offline if there''s no
signal. Supervisors approve from anywhere. The handover report — PDF and Excel —
generates itself when the project closes, instead of being assembled by hand
weeks later.

You run a dedicated T&C team on EHV substations up to 765 kV with many projects going at once. At that volume the handover backlog is an arithmetic problem before it''s anything else.

It''s live at https://optimustesting.com — worth a two-minute look before you
decide whether to reply.

I''d like to run one of your projects on it end to end, free. If it doesn''t save
your team time at handover, you''ve lost nothing but the call.

15 minutes this week?

Parakh Sharma
Optimus Testing
+91 94135 52887'
  FROM public.lead_contacts c
 WHERE d.contact_id = c.id
   AND lower(c.email) = lower('info@elitepowertech.in')
   AND d.status = 'DRAFT';

UPDATE public.outreach_drafts d
   SET subject = 'For your T&C head — commissioning software from IIT Bombay', body = 'Hello,

I''m Parakh Sharma, at IIT Bombay. I''ve built commissioning software for
substation testing teams, and I got this address from your website. **If this
isn''t your area, please forward it to whoever runs testing & commissioning.**

What it does: engineers record test results on site, offline if there''s no
signal. Supervisors approve from anywhere. The handover report — PDF and Excel —
generates itself when the project closes, instead of being assembled by hand
weeks later.

You run T&C to IS standards across EHV substations, transformer yards, RMUs and pad-mount switchgear, on projects in two countries. The more standards and sites in play, the more of the handover pack is manual assembly.

It''s live at https://optimustesting.com — worth a two-minute look before you
decide whether to reply.

I''d like to run one of your projects on it end to end, free. If it doesn''t save
your team time at handover, you''ve lost nothing but the call.

15 minutes this week?

Parakh Sharma
Optimus Testing
+91 94135 52887'
  FROM public.lead_contacts c
 WHERE d.contact_id = c.id
   AND lower(c.email) = lower('info@eternergy.com.in')
   AND d.status = 'DRAFT';
