-- Seeds the phase-1 outreach drafts into outreach_drafts.
--
-- Generated by scripts/gen_draft_seed.py from the same templates and per-company
-- hooks that produce docs/sales/EMAIL_DRAFTS.md, so the copy cannot drift between
-- what is reviewed in the repo and what the panel sends.
--
-- Lead and contact are resolved by name and address at apply time rather than by
-- hardcoded uuid, because the ids differ per environment. A draft whose contact
-- cannot be resolved is skipped rather than inserted with a free-text address --
-- send_outreach_draft refuses to send without a linked contact, so a row like
-- that would be dead weight.
--
-- Idempotent: ON CONFLICT DO NOTHING against the unique contact index, so
-- re-applying cannot produce a second draft to the same person.

INSERT INTO public.outreach_drafts (lead_id, contact_id, to_email, to_name, subject, body)
SELECT l.id, c.id, 'ravi@akuntha.com', 'Ravi Kamdar', 'Commissioning test records at Akuntha — from IIT Bombay', 'Mr Kamdar,

I''m Parakh Sharma, at IIT Bombay. I''ve built TestFlow — commissioning software
for substation testing teams. I got your address from akuntha.com.

What it does: your engineers record test results on site, offline if there''s no
signal. Supervisors approve from anywhere. The handover report — PDF and Excel —
generates itself when the project closes, instead of being assembled by hand
weeks later from whatever is on which laptop.

You''re running erection, T&C and O&M across Gujarat with a lot of substations live at once. That concurrency is exactly where test records stop being findable.

It''s live at https://optimustesting.com — worth a two-minute look before you
decide whether to reply.

I''d like to run one of your projects on it end to end, free. If it doesn''t save
your team time at handover, you''ve lost nothing but the call.

15 minutes this week?

Parakh Sharma
Optimus Testing
+91 94135 52887

If you''d rather not hear from me, reply STOP and I won''t write again.'
  FROM public.leads l
  JOIN public.lead_contacts c ON c.lead_id = l.id AND lower(c.email) = lower('ravi@akuntha.com')
 WHERE l.company_name = 'Akuntha Projects Pvt Ltd'
ON CONFLICT (contact_id) WHERE contact_id IS NOT NULL DO NOTHING;

INSERT INTO public.outreach_drafts (lead_id, contact_id, to_email, to_name, subject, body)
SELECT l.id, c.id, 'mahendra@transerect.com', 'S. V. Mahendra', 'Commissioning test records at Transerect — from IIT Bombay', 'Mr Mahendra,

I''m Parakh Sharma, at IIT Bombay. I''ve built TestFlow — commissioning software
for substation testing teams. I got your address from transerect.com.

What it does: your engineers record test results on site, offline if there''s no
signal. Supervisors approve from anywhere. The handover report — PDF and Excel —
generates itself when the project closes, instead of being assembled by hand
weeks later from whatever is on which laptop.

Transerect is built purely around T&C, so the site test report isn''t a by-product for you — it is the deliverable. That''s the part this makes automatic.

It''s live at https://optimustesting.com — worth a two-minute look before you
decide whether to reply.

I''d like to run one of your projects on it end to end, free. If it doesn''t save
your team time at handover, you''ve lost nothing but the call.

15 minutes this week?

Parakh Sharma
Optimus Testing
+91 94135 52887

If you''d rather not hear from me, reply STOP and I won''t write again.'
  FROM public.leads l
  JOIN public.lead_contacts c ON c.lead_id = l.id AND lower(c.email) = lower('mahendra@transerect.com')
 WHERE l.company_name = 'Transerect Testing & Commissioning Engineers Pvt Ltd'
ON CONFLICT (contact_id) WHERE contact_id IS NOT NULL DO NOTHING;

INSERT INTO public.outreach_drafts (lead_id, contact_id, to_email, to_name, subject, body)
SELECT l.id, c.id, 'enquiry@arraaenergy.com', NULL, 'For your T&C head — commissioning software from IIT Bombay', 'Hello,

I''m Parakh Sharma, at IIT Bombay. I''ve built commissioning software for
substation testing teams, and I got this address from your website. **If this
isn''t your area, please forward it to whoever runs testing & commissioning.**

What it does: engineers record test results on site, offline if there''s no
signal. Supervisors approve from anywhere. The handover report — PDF and Excel —
generates itself when the project closes, instead of being assembled by hand
weeks later.

You test every protection relay type on OMICRON, Megger and Doble, and hand over formal IEC/IEEE test reports at the end. Those kits each produce their own output; the report is still assembled afterwards. That assembly is what this removes.

It''s live at https://optimustesting.com — worth a two-minute look before you
decide whether to reply.

I''d like to run one of your projects on it end to end, free. If it doesn''t save
your team time at handover, you''ve lost nothing but the call.

15 minutes this week?

Parakh Sharma
Optimus Testing
+91 94135 52887

Reply STOP and I won''t write again.'
  FROM public.leads l
  JOIN public.lead_contacts c ON c.lead_id = l.id AND lower(c.email) = lower('enquiry@arraaenergy.com')
 WHERE l.company_name = 'ARRAA Energy'
ON CONFLICT (contact_id) WHERE contact_id IS NOT NULL DO NOTHING;

INSERT INTO public.outreach_drafts (lead_id, contact_id, to_email, to_name, subject, body)
SELECT l.id, c.id, 'enquiry@gkexpertise.com', NULL, 'For your T&C head — commissioning software from IIT Bombay', 'Hello,

I''m Parakh Sharma, at IIT Bombay. I''ve built commissioning software for
substation testing teams, and I got this address from your website. **If this
isn''t your area, please forward it to whoever runs testing & commissioning.**

What it does: engineers record test results on site, offline if there''s no
signal. Supervisors approve from anywhere. The handover report — PDF and Excel —
generates itself when the project closes, instead of being assembled by hand
weeks later.

You''re running OMICRON, Megger and Doble across every major relay make, AIS and GIS, and writing site test reports off the back of all of it. The reports are the part I''m trying to make automatic.

It''s live at https://optimustesting.com — worth a two-minute look before you
decide whether to reply.

I''d like to run one of your projects on it end to end, free. If it doesn''t save
your team time at handover, you''ve lost nothing but the call.

15 minutes this week?

Parakh Sharma
Optimus Testing
+91 94135 52887

Reply STOP and I won''t write again.'
  FROM public.leads l
  JOIN public.lead_contacts c ON c.lead_id = l.id AND lower(c.email) = lower('enquiry@gkexpertise.com')
 WHERE l.company_name = 'GK Expertise / GK Power Expertise Pvt Ltd'
ON CONFLICT (contact_id) WHERE contact_id IS NOT NULL DO NOTHING;

INSERT INTO public.outreach_drafts (lead_id, contact_id, to_email, to_name, subject, body)
SELECT l.id, c.id, 'info@powertestasia.com', NULL, 'For your T&C head — commissioning software from IIT Bombay', 'Hello,

I''m Parakh Sharma, at IIT Bombay. I''ve built commissioning software for
substation testing teams, and I got this address from your website. **If this
isn''t your area, please forward it to whoever runs testing & commissioning.**

What it does: engineers record test results on site, offline if there''s no
signal. Supervisors approve from anywhere. The handover report — PDF and Excel —
generates itself when the project closes, instead of being assembled by hand
weeks later.

As an independent TPIA your report is the product — clients pay for its credibility precisely because you''re not tied to an OEM. Thirty years of that reputation is a lot to leave sitting in files on individual laptops.

It''s live at https://optimustesting.com — worth a two-minute look before you
decide whether to reply.

I''d like to run one of your projects on it end to end, free. If it doesn''t save
your team time at handover, you''ve lost nothing but the call.

15 minutes this week?

Parakh Sharma
Optimus Testing
+91 94135 52887

Reply STOP and I won''t write again.'
  FROM public.leads l
  JOIN public.lead_contacts c ON c.lead_id = l.id AND lower(c.email) = lower('info@powertestasia.com')
 WHERE l.company_name = 'Powertest Asia Pvt Ltd (PtA)'
ON CONFLICT (contact_id) WHERE contact_id IS NOT NULL DO NOTHING;

INSERT INTO public.outreach_drafts (lead_id, contact_id, to_email, to_name, subject, body)
SELECT l.id, c.id, 'cv@sunjay.in', NULL, 'For your T&C head — commissioning software from IIT Bombay', 'Hello,

I''m Parakh Sharma, at IIT Bombay. I''ve built commissioning software for
substation testing teams, and I got this address from your website. **If this
isn''t your area, please forward it to whoever runs testing & commissioning.**

What it does: engineers record test results on site, offline if there''s no
signal. Supervisors approve from anywhere. The handover report — PDF and Excel —
generates itself when the project closes, instead of being assembled by hand
weeks later.

You cover ABB, Siemens, GE, SEL and Alstom relays across Tamil Nadu — every make with its own output format, and one coherent handover pack expected at the end of the job.

It''s live at https://optimustesting.com — worth a two-minute look before you
decide whether to reply.

I''d like to run one of your projects on it end to end, free. If it doesn''t save
your team time at handover, you''ve lost nothing but the call.

15 minutes this week?

Parakh Sharma
Optimus Testing
+91 94135 52887

Reply STOP and I won''t write again.'
  FROM public.leads l
  JOIN public.lead_contacts c ON c.lead_id = l.id AND lower(c.email) = lower('cv@sunjay.in')
 WHERE l.company_name = 'Sun and Jay Engineering Consultants Pvt Ltd'
ON CONFLICT (contact_id) WHERE contact_id IS NOT NULL DO NOTHING;

INSERT INTO public.outreach_drafts (lead_id, contact_id, to_email, to_name, subject, body)
SELECT l.id, c.id, 'marketing@volt-age.in', NULL, 'For your T&C head — commissioning software from IIT Bombay', 'Hello,

I''m Parakh Sharma, at IIT Bombay. I''ve built commissioning software for
substation testing teams, and I got this address from your website. **If this
isn''t your area, please forward it to whoever runs testing & commissioning.**

What it does: engineers record test results on site, offline if there''s no
signal. Supervisors approve from anywhere. The handover report — PDF and Excel —
generates itself when the project closes, instead of being assembled by hand
weeks later.

You''re growing fast across solar EPC and substation O&M in Maharashtra. Growth is exactly when test records stop fitting in whatever worked at ten projects.

It''s live at https://optimustesting.com — worth a two-minute look before you
decide whether to reply.

I''d like to run one of your projects on it end to end, free. If it doesn''t save
your team time at handover, you''ve lost nothing but the call.

15 minutes this week?

Parakh Sharma
Optimus Testing
+91 94135 52887

Reply STOP and I won''t write again.'
  FROM public.leads l
  JOIN public.lead_contacts c ON c.lead_id = l.id AND lower(c.email) = lower('marketing@volt-age.in')
 WHERE l.company_name = 'Voltage Infra Pvt Ltd'
ON CONFLICT (contact_id) WHERE contact_id IS NOT NULL DO NOTHING;

INSERT INTO public.outreach_drafts (lead_id, contact_id, to_email, to_name, subject, body)
SELECT l.id, c.id, 'info@gtllab.org', NULL, 'For your T&C head — commissioning software from IIT Bombay', 'Hello,

I''m Parakh Sharma, at IIT Bombay. I''ve built commissioning software for
substation testing teams, and I got this address from your website. **If this
isn''t your area, please forward it to whoever runs testing & commissioning.**

What it does: engineers record test results on site, offline if there''s no
signal. Supervisors approve from anywhere. The handover report — PDF and Excel —
generates itself when the project closes, instead of being assembled by hand
weeks later.

NABL accreditation means every result has to be traceable to who recorded it and when. That trail is kept automatically here rather than reconstructed when someone asks for it.

It''s live at https://optimustesting.com — worth a two-minute look before you
decide whether to reply.

I''d like to run one of your projects on it end to end, free. If it doesn''t save
your team time at handover, you''ve lost nothing but the call.

15 minutes this week?

Parakh Sharma
Optimus Testing
+91 94135 52887

Reply STOP and I won''t write again.'
  FROM public.leads l
  JOIN public.lead_contacts c ON c.lead_id = l.id AND lower(c.email) = lower('info@gtllab.org')
 WHERE l.company_name = 'Ghaziabad Testing Laboratories Pvt Ltd'
ON CONFLICT (contact_id) WHERE contact_id IS NOT NULL DO NOTHING;

INSERT INTO public.outreach_drafts (lead_id, contact_id, to_email, to_name, subject, body)
SELECT l.id, c.id, 'info@elitepowertech.in', NULL, 'For your T&C head — commissioning software from IIT Bombay', 'Hello,

I''m Parakh Sharma, at IIT Bombay. I''ve built commissioning software for
substation testing teams, and I got this address from your website. **If this
isn''t your area, please forward it to whoever runs testing & commissioning.**

What it does: engineers record test results on site, offline if there''s no
signal. Supervisors approve from anywhere. The handover report — PDF and Excel —
generates itself when the project closes, instead of being assembled by hand
weeks later.

You run a dedicated T&C team on EHV substations up to 765 kV with many projects going at once. At that volume the handover backlog is an arithmetic problem before it''s anything else.

It''s live at https://optimustesting.com — worth a two-minute look before you
decide whether to reply.

I''d like to run one of your projects on it end to end, free. If it doesn''t save
your team time at handover, you''ve lost nothing but the call.

15 minutes this week?

Parakh Sharma
Optimus Testing
+91 94135 52887

Reply STOP and I won''t write again.'
  FROM public.leads l
  JOIN public.lead_contacts c ON c.lead_id = l.id AND lower(c.email) = lower('info@elitepowertech.in')
 WHERE l.company_name = 'Elite Powertech Pvt Ltd (EPPL)'
ON CONFLICT (contact_id) WHERE contact_id IS NOT NULL DO NOTHING;

INSERT INTO public.outreach_drafts (lead_id, contact_id, to_email, to_name, subject, body)
SELECT l.id, c.id, 'info@eternergy.com.in', NULL, 'For your T&C head — commissioning software from IIT Bombay', 'Hello,

I''m Parakh Sharma, at IIT Bombay. I''ve built commissioning software for
substation testing teams, and I got this address from your website. **If this
isn''t your area, please forward it to whoever runs testing & commissioning.**

What it does: engineers record test results on site, offline if there''s no
signal. Supervisors approve from anywhere. The handover report — PDF and Excel —
generates itself when the project closes, instead of being assembled by hand
weeks later.

You run T&C to IS standards across EHV substations, transformer yards, RMUs and pad-mount switchgear, on projects in two countries. The more standards and sites in play, the more of the handover pack is manual assembly.

It''s live at https://optimustesting.com — worth a two-minute look before you
decide whether to reply.

I''d like to run one of your projects on it end to end, free. If it doesn''t save
your team time at handover, you''ve lost nothing but the call.

15 minutes this week?

Parakh Sharma
Optimus Testing
+91 94135 52887

Reply STOP and I won''t write again.'
  FROM public.leads l
  JOIN public.lead_contacts c ON c.lead_id = l.id AND lower(c.email) = lower('info@eternergy.com.in')
 WHERE l.company_name = 'Eternergy Engineering Pvt Ltd'
ON CONFLICT (contact_id) WHERE contact_id IS NOT NULL DO NOTHING;
