export interface NameplateFieldDef {
  key: string;
  label: string;
  type?: 'text' | 'number';
  unit?: string;
  span?: 'full';
}

export const NAMEPLATE_FIELDS: Record<string, NameplateFieldDef[]> = {
  POWER_TRANSFORMER: [
    { key: 'manufacturer', label: 'Manufacturer' },
    { key: 'serial_number', label: 'Serial Number' },
    { key: 'year_of_manufacture', label: 'Year of Manufacture', type: 'number' },
    { key: 'rating_mva', label: 'Rating', unit: 'MVA', type: 'number' },
    { key: 'rated_frequency', label: 'Rated Frequency', unit: 'Hz', type: 'number' },
    { key: 'cooling_type', label: 'Cooling Type' },
    { key: 'vector_group', label: 'Vector Group' },
    { key: 'voltage_hv', label: 'HV Voltage', unit: 'kV', type: 'number' },
    { key: 'voltage_lv', label: 'LV Voltage', unit: 'kV', type: 'number' },
    { key: 'voltage_tv', label: 'TV Voltage (3-winding)', unit: 'kV', type: 'number' },
    { key: 'rated_current_hv', label: 'Rated Current HV', unit: 'A', type: 'number' },
    { key: 'rated_current_lv', label: 'Rated Current LV', unit: 'A', type: 'number' },
    { key: 'impedance_percent', label: 'Impedance', unit: '%', type: 'number' },
    { key: 'tap_range', label: 'Tap Range' },
  ],
  CT: [
    { key: 'manufacturer', label: 'Manufacturer' },
    { key: 'serial_number', label: 'Serial Number' },
    { key: 'year_of_manufacture', label: 'Year of Manufacture', type: 'number' },
    { key: 'rated_voltage', label: 'Rated Voltage', unit: 'kV', type: 'number' },
    { key: 'rated_current_primary', label: 'Primary Current', unit: 'A', type: 'number' },
    { key: 'rated_current_secondary', label: 'Secondary Current', unit: 'A', type: 'number' },
    { key: 'accuracy_class', label: 'Accuracy Class' },
    { key: 'burden_va', label: 'Burden', unit: 'VA', type: 'number' },
    { key: 'short_time_current', label: 'Short Time Current', unit: 'kA', type: 'number' },
    { key: 'num_cores', label: 'Number of Cores', type: 'number' },
  ],
  CVT: [
    { key: 'manufacturer', label: 'Manufacturer' },
    { key: 'serial_number', label: 'Serial Number' },
    { key: 'year_of_manufacture', label: 'Year of Manufacture', type: 'number' },
    { key: 'rated_voltage', label: 'Rated Voltage', unit: 'kV', type: 'number' },
    { key: 'rated_burden_va', label: 'Rated Burden', unit: 'VA', type: 'number' },
    { key: 'accuracy_class', label: 'Accuracy Class' },
    { key: 'rated_frequency', label: 'Rated Frequency', unit: 'Hz', type: 'number' },
    { key: 'capacitance_c1', label: 'Capacitance C1', unit: 'pF', type: 'number' },
    { key: 'capacitance_c2', label: 'Capacitance C2', unit: 'pF', type: 'number' },
    { key: 'secondary_voltage', label: 'Secondary Voltage', unit: 'V', type: 'number' },
  ],
  LA: [
    { key: 'manufacturer', label: 'Manufacturer' },
    { key: 'serial_number', label: 'Serial Number' },
    { key: 'year_of_manufacture', label: 'Year of Manufacture', type: 'number' },
    { key: 'rated_voltage', label: 'Rated Voltage', unit: 'kV', type: 'number' },
    { key: 'mcov_kv', label: 'MCOV', unit: 'kV', type: 'number' },
    { key: 'discharge_current', label: 'Discharge Current', unit: 'kA', type: 'number' },
    { key: 'energy_class', label: 'Energy Class' },
    { key: 'protection_level', label: 'Protection Level', unit: 'kV (peak)', type: 'number' },
  ],
  SF6_BREAKER: [
    { key: 'manufacturer', label: 'Manufacturer' },
    { key: 'serial_number', label: 'Serial Number' },
    { key: 'year_of_manufacture', label: 'Year of Manufacture', type: 'number' },
    { key: 'rated_voltage', label: 'Rated Voltage', unit: 'kV', type: 'number' },
    { key: 'rated_current', label: 'Rated Current', unit: 'A', type: 'number' },
    { key: 'rated_sc_current', label: 'Rated SC Current', unit: 'kA', type: 'number' },
    { key: 'operating_mechanism', label: 'Operating Mechanism' },
    { key: 'sf6_pressure', label: 'SF6 Rated Pressure', unit: 'bar', type: 'number' },
    { key: 'num_breaks_per_pole', label: 'Breaks per Pole', type: 'number' },
    { key: 'control_voltage', label: 'Control Voltage', unit: 'V DC', type: 'number' },
  ],
  ISOLATOR: [
    { key: 'manufacturer', label: 'Manufacturer' },
    { key: 'serial_number', label: 'Serial Number' },
    { key: 'year_of_manufacture', label: 'Year of Manufacture', type: 'number' },
    { key: 'rated_voltage', label: 'Rated Voltage', unit: 'kV', type: 'number' },
    { key: 'rated_current', label: 'Rated Current', unit: 'A', type: 'number' },
    { key: 'rated_sc_current', label: 'Rated SC Current', unit: 'kA', type: 'number' },
    { key: 'isolator_type', label: 'Type (e.g. Centre-break, Double-break)' },
    { key: 'earthing_switch', label: 'Earthing Switch (Yes / No)' },
  ],
  VCB: [
    { key: 'manufacturer', label: 'Manufacturer' },
    { key: 'serial_number', label: 'Serial Number' },
    { key: 'year_of_manufacture', label: 'Year of Manufacture', type: 'number' },
    { key: 'rated_voltage', label: 'Rated Voltage', unit: 'kV', type: 'number' },
    { key: 'rated_current', label: 'Rated Current', unit: 'A', type: 'number' },
    { key: 'rated_sc_current', label: 'Rated SC Current', unit: 'kA', type: 'number' },
    { key: 'operating_mechanism', label: 'Operating Mechanism' },
    { key: 'control_voltage', label: 'Control Voltage', unit: 'V DC', type: 'number' },
  ],
  EARTH_PIT: [
    { key: 'location', label: 'Location / Tag', span: 'full' },
    { key: 'depth_m', label: 'Depth', unit: 'm', type: 'number' },
    { key: 'electrode_material', label: 'Electrode Material' },
    { key: 'soil_type', label: 'Soil Type' },
    { key: 'chemical_treatment', label: 'Chemical Treatment (Yes / No)' },
  ],
  VT: [
    { key: 'equipment_location', label: 'Equipment Location / Bay', span: 'full' },
    { key: 'phase', label: 'Phase (R / Y / B)' },
    { key: 'rated_primary_voltage', label: 'Rated Primary Voltage' },
    { key: 'rated_frequency', label: 'Rated Frequency', unit: 'Hz', type: 'number' },
  ],
};
